-- MySQL Script generated by MySQL Workbench
-- Sun May  1 11:51:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema manage_doctor_booking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `manage_doctor_booking` ;

-- -----------------------------------------------------
-- Schema manage_doctor_booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manage_doctor_booking` DEFAULT CHARACTER SET utf8 ;
USE `manage_doctor_booking` ;

-- -----------------------------------------------------
-- Table `manage_doctor_booking`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manage_doctor_booking`.`role` ;

CREATE TABLE IF NOT EXISTS `manage_doctor_booking`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `manage_doctor_booking`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manage_doctor_booking`.`user` ;

CREATE TABLE IF NOT EXISTS `manage_doctor_booking`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL DEFAULT NULL,
  `sex` VARCHAR(10) NULL DEFAULT NULL,
  `phone` BIGINT NOT NULL,
  `date_of_birth` DATETIME NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `manage_doctor_booking`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `manage_doctor_booking`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manage_doctor_booking`.`calendar` ;

CREATE TABLE IF NOT EXISTS `manage_doctor_booking`.`calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `time` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `doctor_id`),
  INDEX `fk_calendar_user1_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_calendar_user1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `manage_doctor_booking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `manage_doctor_booking`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manage_doctor_booking`.`department` ;

CREATE TABLE IF NOT EXISTS `manage_doctor_booking`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `manage_doctor_booking`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manage_doctor_booking`.`history` ;

CREATE TABLE IF NOT EXISTS `manage_doctor_booking`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `symptom_content` VARCHAR(100) NULL DEFAULT NULL,
  `calendar_id` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `patient_id`, `calendar_id`),
  INDEX `fk_history_user1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_history_calendar1_idx` (`calendar_id` ASC) VISIBLE,
  CONSTRAINT `fk_history_user1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `manage_doctor_booking`.`user` (`id`),
  CONSTRAINT `fk_history_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `manage_doctor_booking`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `manage_doctor_booking`.`symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manage_doctor_booking`.`symptom` ;

CREATE TABLE IF NOT EXISTS `manage_doctor_booking`.`symptom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`, `department_id`),
  INDEX `fk_symptom_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_symptom_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `manage_doctor_booking`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manage_doctor_booking`.`department_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manage_doctor_booking`.`department_has_user` ;

CREATE TABLE IF NOT EXISTS `manage_doctor_booking`.`department_has_user` (
  `department_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`department_id`, `user_id`),
  INDEX `fk_department_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_department_has_user_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_has_user_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `manage_doctor_booking`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_department_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `manage_doctor_booking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
